//gtr
GET http://localhost:8880/hello
#Accept: application/json

> {%
// client.test("test-hello", function(){
//     client.log("测试/hello接口");
//     client.log(response.body);
//     client.log(JSON.stringify(response.body));
//     client.assert(response.status === 200, "返回码不是200");
//     client.assert(response.body === "Hello World", "结果验证失败");
// });
 %}
###

//ptrp
POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

GET http://localhost:8880/test/list


###

GET http://localhost:8880/test/redis/set/test/123
Accept: application/json

###

GET http://localhost:8880/redis/get/216868475686227968
Accept: application/json

###

POST http://localhost:8880/ebook/save
Content-Type: application/json

{}
###
